using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Day7OOP.Partial
{
    // Auto generated by EF
    public partial class Employee
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Age { get; set; }
        public partial void print(); // cant be sealed/virtual and partial
        public void Test()
        {
            Console.WriteLine("Hello from Partial Class");
            print();
        }
    }
}
